# Q1. 자동차 배기량에 따라 고속도로 연비가 다른지 알아볼라 함
- displ(배기량)이 4이하인 차랑 5이상인 차 중 어떤 차의 hwy(고속도로 연비) 평균이 더 높은지 알아봐라

In [3]:
import pandas as pd

mpg = pd.read_csv('data/mpg.csv')

mpg_a = mpg.query('displ <= 4')
mpg_b = mpg.query('displ >= 5')

In [4]:
mpg_a

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,category
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact
...,...,...,...,...,...,...,...,...,...,...,...
229,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize
230,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize
231,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize
232,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize
233,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize

In [5]:
# 배기량이 4 이하의 평균
mpg_a['hwy'].mean()

np.float64(25.96319018404908)

In [6]:
# 배기량이 5 이상 평균
mpg_b['hwy'].mean()

np.float64(18.07894736842105)

# Q2. 아우디와 도요다중 어느 manufacturer의 cty(도시 연비) 평균
- 뭐가 더 높노??

In [9]:
mpg_audi = mpg.query('manufacturer == "audi"')
mpg_toyota = mpg.query('manufacturer == "toyota"')

In [10]:
# audi 연비 평균
mpg_audi['cty'].mean()

np.float64(17.61111111111111)

In [11]:
# toyota 연비 평균
mpg_toyota['cty'].mean()

np.float64(18.529411764705884)

# Q3. chevrolet, ford, honda자동차의 고속도로 연비 평균
- 세 회사의 데이터 추출 하고 hwy 전체 평균 ㄱ

In [15]:
mpg_avg = mpg.query('manufacturer in["chevrolet", "ford", "honda"]')
mpg_avg

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,category
18,chevrolet,c1500 suburban 2wd,5.3,2008,8,auto(l4),r,14,20,r,suv
19,chevrolet,c1500 suburban 2wd,5.3,2008,8,auto(l4),r,11,15,e,suv
20,chevrolet,c1500 suburban 2wd,5.3,2008,8,auto(l4),r,14,20,r,suv
21,chevrolet,c1500 suburban 2wd,5.7,1999,8,auto(l4),r,13,17,r,suv
22,chevrolet,c1500 suburban 2wd,6.0,2008,8,auto(l4),r,12,17,r,suv
23,chevrolet,corvette,5.7,1999,8,manual(m6),r,16,26,p,2seater
24,chevrolet,corvette,5.7,1999,8,auto(l4),r,15,23,p,2seater
25,chevrolet,corvette,6.2,2008,8,manual(m6),r,16,26,p,2seater
26,chevrolet,corvette,6.2,2008,8,auto(s6),r,15,25,p,2seater
27,chevrolet,corvette,7.0,2008,8,manual(m6),r,15,24,p,2seater
28,chevrolet,k1500 tahoe 4wd,5.3,2008,8,auto(l4),4,14,19,r,suv
29,chevrolet,k1500 tahoe 4wd,5.3,2008,8,auto(l4),4,11,14,e,suv
30,chevrolet,k1500 tahoe 4wd,5.7,1999,8,auto(l4),4,11,15,r,suv
31,chevrolet,k1500 tahoe 4wd,6.5,1999,8,auto(l4),4,14,17,d,suv
32,chevrolet,malibu,2.4,1999,4,auto(l4),f,19,27,r,midsize
33,chevrolet,malibu,2.4,2008,4,auto(l4),f,22,30,r,midsize
34,chevrolet,malibu,3.1,1999,6,auto(l4),f,18,26,r,midsize
35,chevrolet,malibu,3.5,2008,6,auto(l4),f,18,29,r,midsize
36,chevrolet,malibu,3.6,2008,6,auto(s6),f,17,26,r,midsize
74,ford,expedition 2wd,4.6,1999,8,auto(l4),r,11,17,r,suv
75,ford,expedition 2wd,5.4,1999,8,auto(l4),r,11,17,r,suv
76,ford,expedition 2wd,5.4,2008,8,auto(l6),r,12,18,r,suv
77,ford,explorer 4wd,4.0,1999,6,auto(l5),4,14,17,r,suv
78,ford,explorer 4wd,4.0,1999,6,manual(m5),4,15,19,r,suv
79,ford,explorer 4wd,4.0,1999,6,auto(l5),4,14,17,r,suv
80,ford,explorer 4wd,4.0,2008,6,auto(l5),4,13,19,r,suv
81,ford,explorer 4wd,4.6,2008,8,auto(l6),4,13,19,r,suv
82,ford,explorer 4wd,5.0,1999,8,auto(l4),4,13,17,r,suv
83,ford,f150 pickup 4wd,4.2,1999,6,auto(l4),4,14,17,r,pickup
84,ford,f150 pickup 4wd,4.2,1999,6,manual(m5),4,14,17,r,pickup
85,ford,f150 pickup 4wd,4.6,1999,8,manual(m5),4,13,16,r,pickup
86,ford,f150 pickup 4wd,4.6,1999,8,auto(l4),4,13,16,r,pickup
87,ford,f150 pickup 4wd,4.6,2008,8,auto(l4),4,13,17,r,pickup
88,ford,f150 pickup 4wd,5.4,1999,8,auto(l4),4,11,15,r,pickup
89,ford,f150 pickup 4wd,5.4,2008,8,auto(l4),4,13,17,r,pickup
90,ford,mustang,3.8,1999,6,manual(m5),r,18,26,r,subcompact
91,ford,mustang,3.8,1999,6,auto(l4),r,18,25,r,subcompact
92,ford,mustang,4.0,2008,6,manual(m5),r,17,26,r,subcompact
93,ford,mustang,4.0,2008,6,auto(l5),r,16,24,r,subcompact
94,ford,mustang,4.6,1999,8,auto(l4),r,15,21,r,subcompact
95,ford,mustang,4.6,1999,8,manual(m5),r,15,22,r,subcompact
96,ford,mustang,4.6,2008,8,manual(m5),r,15,23,r,subcompact
97,ford,mustang,4.6,2008,8,auto(l5),r,15,22,r,subcompact
98,ford,mustang,5.4,2008,8,manual(m6),r,14,20,p,subcompact
99,honda,civic,1.6,1999,4,manual(m5),f,28,33,r,subcompact
100,honda,civic,1.6,1999,4,auto(l4),f,24,32,r,subcompact
101,honda,civic,1.6,1999,4,manual(m5),f,25,32,r,subcompact
102,honda,civic,1.6,1999,4,manual(m5),f,23,29,p,subcompact
103,honda,civic,1.6,1999,4,auto(l4),f,24,32,r,subcompact
104,honda,civic,1.8,2008,4,manual(m5),f,26,34,r,subcompact
105,honda,civic,1.8,2008,4,auto(l5),f,25,36,r,subcompact
106,honda,civic,1.8,2008,4,auto(l5),f,24,36,c,subcompact
107,honda,civic,2.0,2008,4,manual(m6),f,21,29,p,subcompact

In [16]:
mpg_avg['hwy'].mean()

np.float64(22.50943396226415)